# Generated by Django 5.1.1 on 2024-11-21 09:55

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinematograf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oras', models.CharField(max_length=50)),
                ('strada', models.CharField(max_length=50)),
                ('numar', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Difuzare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timp_start', models.TimeField()),
                ('este_3D', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoare', models.PositiveIntegerField(default=0)),
                ('tip', models.CharField(default='MISSING', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(max_length=50, unique=True)),
                ('descriere', models.TextField(max_length=500, null=True)),
                ('imagine', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('durata', models.DurationField(default=datetime.timedelta(0))),
                ('data_adaugare', models.DateTimeField(default=django.utils.timezone.now, help_text='Format: YYYY-MM-DD HH:MM:SS')),
                ('data_aparitie', models.DateField()),
                ('secol_aparitie', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telefon', models.CharField(blank=True, max_length=15)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Bilet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pret', models.DecimalField(decimal_places=2, max_digits=4)),
                ('nr_loc', models.PositiveIntegerField()),
                ('data_cumparat', models.DateTimeField(default=django.utils.timezone.now)),
                ('difuzare', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.difuzare')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.discount')),
            ],
        ),
        migrations.AddField(
            model_name='difuzare',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.film'),
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=50, unique=True)),
                ('descriere', models.TextField(null=True)),
                ('filme', models.ManyToManyField(to='app1.film')),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numar', models.PositiveIntegerField()),
                ('nr_locuri', models.PositiveIntegerField(choices=[(60, 'Mica'), (90, 'Mare')], default=60)),
                ('cinematograf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.cinematograf')),
            ],
        ),
        migrations.AddField(
            model_name='difuzare',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.sala'),
        ),
    ]
