# Generated by Django 5.1.1 on 2024-12-09 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_vizualizari'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='categorii',
            field=models.ManyToManyField(to='app1.categorie'),
        ),
        migrations.CreateModel(
            name='Promotii',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=50, unique=True)),
                ('data_creare', models.DateField()),
                ('data_expirare', models.DateField()),
                ('discount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.discount')),
                ('oras', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.cinematograf')),
            ],
        ),
    ]
