# Generated by Django 5.1.1 on 2024-12-09 20:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_promotii_oras_promotii_limita_utilizari_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=50, unique=True)),
                ('data_creare', models.DateField(default=django.utils.timezone.now)),
                ('data_expirare', models.DateField()),
                ('discount', models.IntegerField(default=0)),
                ('limita_utilizari', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Promotii',
        ),
    ]
