# Generated by Django 5.1.1 on 2024-12-17 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_promotie_delete_promotii'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': (('vizualizeaza_oferta', 'Vizualizeaza oferta'),)},
        ),
        migrations.AlterField(
            model_name='film',
            name='durata',
            field=models.DurationField(default=datetime.timedelta(0), null=True),
        ),
    ]
