# Generated by Django 5.1.1 on 2024-12-19 12:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_customuser_options_alter_film_durata'),
    ]

    operations = [
        migrations.AddField(
            model_name='difuzare',
            name='data',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
