# Generated by Django 5.1.1 on 2025-01-03 19:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_difuzare_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='data_autentificare',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
