# Generated by Django 5.1.1 on 2025-01-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_alter_customuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='difuzare',
            name='nr_locuri',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
