# Generated by Django 5.1.1 on 2025-01-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_difuzare_pret_bilet'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotie',
            name='categorii',
            field=models.ManyToManyField(related_name='promotii', to='app1.categorie'),
        ),
    ]
