# Generated by Django 5.1.1 on 2025-01-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_comanda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='filme',
            field=models.ManyToManyField(related_name='actori', to='app1.film'),
        ),
    ]
